name: Generate Daily Sales

on:
  schedule:
    # Roda todo dia às 3h da manhã (UTC)
    - cron: '0 3 * * *'

  #schedule:
  #  # Gera vendas a cada 3 minutos
  #  - cron: '*/3 * * * *' # 
  
  workflow_dispatch:

jobs:
  generate-sales:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14'
      
      - name: Install dependencies
        run: |
          pip install gspread oauth2client python-dotenv
      
      - name: Generate sales
        run: |
          python src/generate_daily_sales.py
      